# Generated by Django 2.2 on 2020-09-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
