# Generated by Django 2.2 on 2020-09-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200907_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='usertype',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
