# Generated by Django 2.2 on 2020-09-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_registration_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
