# Generated by Django 2.2 on 2020-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_registration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
