# Generated by Django 2.2 on 2020-10-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
