# Generated by Django 2.2 on 2020-10-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='images/user.png', upload_to='images/'),
        ),
    ]
